sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3307
    database: sky_take_out
    username: root
    password: root
  redis:
    port: 6379
    host: localhost
    database: 0
  liff:
    end-point-url: https://fancy-torrone-30a781.netlify.app
    appid: 2002542651-30wDwKnW
    url: https://liff.line.me/2002542651-30wDwKnW